---
swagger: "2.0"
info:
  description: "This is API of a rythme game calls \"Group Rei\".\n
  It is for our school project"
  version: "0.0.0"
  title: "Group Rei"
  termsOfService: "https://github.com/ericchang922"
  contact:
    email: "ericchang922@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "http://localhost"
basePath: "/v0"
tags:
- name: "account"
  description: "包含登入及帳號管理等功能"
  externalDocs: 
    description: "參考資料"
    url: "https://google.com/"
    
- name: "chip"
  description: "晶片相關功能"
  externalDocs:
    description: "晶片為角色技能相關道具"
    url: ""

schemes:
- "https"
- "http"
paths:

# 帳號
  /account/login: # 登入
    post: # 種類
      tags: # 分類的標籤
        - "account"
      summary: "使用者登入" # 摘要
      description: "" #細節
      operationId: "login"
      consumes: # 請求格式
        - "application/json"
      produces: # 回傳格式
        - "application/json"
      parameters: # 請求結構
        - name: "body"
          in: "body"
          description: "傳出帳號密碼，密碼使用MD5"
          required: true # 是否為必要條件
          schema: 
            $ref: "#/definitions/LoginData"
      responses: # 回傳
        200: # 成功
          description: "login successful"
          schema: 
            $ref: "#/definitions/UserData"
        400:
          description: "login failed"
          schema: 
            $ref: "#/definitions/BadRequest"
            
      security:
        - rei_auth:
          - "read:account"

# 晶片
  /chip/upgrade:
    post:
      tags:
      - "chip"
      summary: "升級晶片"
      description: ""
      operationId: "upgrade"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/ChipUpgradeData"
      responses: 
        200:
          description: "upgrade successful"
          schema: 
            $ref: "#/definitions/ChipUpgradeResult"
        400:
          description: "upgrade failed"
          schema: 
            $ref: "#/definitions/BadRequest"
          

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "https://petstore.swagger.io/oauth/authorize"
    flow: "implicit"
    scopes:
      read:pets: "read your pets"
      write:pets: "modify pets in your account"
      
# schema
definitions:
  # public
  BadRequest: # 錯誤格式
    type: "object"
    properties: 
      statusCode:
        type: "integer"
        format: "int"
      failedMsg:
        type: "string"
  # account
  LoginData: # 帳號密碼
    type: "object"
    properties: 
      uid:
        type: "string"
      password:
        type: "string"
        
  UserData: # 使用者資料
    type: "object"
    properties: 
      name:
        type: "string"
      birthday:
        type: "datetime"
        format: "date"
      phone:
        type: "string"
      memberLevel:
        type: "integer"
        format: "int"
        description: "金銀銅..."
      mail:
        type: "string"
        
  # chip
  ChipUpgradeData: # 晶片強化資料
    type: "object"
    properties: 
      uid:
        type: "string"
      token:
        type: "string"
      serialNum:
        type: "integer"
      typeId:
        type: "integer"
      U:
        type: "array"
        items: 
          type: "object"
          properties: 
            UType:
              type: "integer"
            Unum:
              type: "integer"
      mu: # 立日
        type: "array"
        items: 
          type: "object"
          properties: 
            having:
              type: "integer"
            cost:
              type: "integer"
              
  ChipUpgradeResult: # 晶片強化結果
    type: "object"
    properties: 
      mu:
        type: "integer"
      expAfterUpgrade:
        type: "number"
        format: "double"
    




externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
